### ISSUE TITLE
Zoom in on Chicago makes data disappear

### ISSUE THREAD

**Issue by glassdimly** [Brian393/petropolis#3]
Go to https://map.environmentalobservatory.net/#/petropolis/chicago

## Reproduction
* Click the "+" icon
* See that all pipeline data disappears on zoom

## Expectation
* Data should not disappear on zoom

**Comment by Brian393** [comment]
Dear Jeremy -

Thanks for all these ideas which I will implement over the next few days.

I thought our meeting last night was really productive. Your focus and
Charity's contributions were really appreciated, David's too. If we keep up
that kind of clarity we will get somewhere!

Till soon, Brian

**Comment by Brian393** [comment]
This is now irrelevant because we got rid of those videos.
