### ISSUE TITLE
Refinery icon is too complex

### ISSUE THREAD

**Issue by glassdimly** [Brian393/petropolis#5]
This refinery image:
![image](https://user-images.githubusercontent.com/1361104/76374250-a8275d00-6310-11ea-9204-feff5c663840.png)

Is too complicated and makes the map confusing.

**Comment by Brian393** [comment]
I changed it but always open to other suggestions. It would be good to change the size on zoom so that the map is uncluttered at continental scale, I think that requires writing a function.
