### ISSUE TITLE
Geoserver layer preview

### ISSUE THREAD

**Issue by Brian393** [Brian393/petropolis#57]
Geoserver layer preview doesn't work.

When you click it, the address seems to be localhost:

http://geoserver:8080/geoserver/petropolis/wms?service=WMS&version=1.1.0&request=GetMap&layers=petropolis%3Aall_pipes&bbox=-150.992004394531%2C26.6549987792969%2C-70.2989959716797%2C70.5100021362305&width=768&height=417&srs=EPSG%3A4326&format=application/openlayers

**Comment by majkshkurti** [comment]
@Brian393 This is fixed now. Can you check if it works for you ?

**Comment by Brian393** [comment]
@majkshkurti 
Openlayers preview works great and so does file export! Thanks.
